apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nohate-ingress
  labels:
    app: nohate-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt
spec:
  tls:
  - secretName: "apps-subdomain-tls"
    hosts:
    - "apps.datexis.com"
  rules:
  - host: "apps.datexis.com"
    http:
      paths:
      - path: /nohate
        backend:
          serviceName: nohate-api
          servicePort: 1337